### ISSUE TITLE
AR Markers detected error in pick_and_place demo

### ISSUE THREAD

**Issue by EndlessLoops** [ROBOTIS-GIT/turtlebot3_manipulation#16]
**Problem Statement**

when I tested the pick_and_place demo in the real environment，I found the problem it can't detect the ar markers. But it can work when I tested it independently.

**Error Info**

```
ubuntu@Turtlebot3-virtual-machine:~$ roslaunch open_manipulator_with_tb3_tools task_controller.launch
... logging to /home/ubuntu/.ros/log/fbc4b996-f608-11e9-b375-000c2965f318/roslaunch-Turtlebot3-virtual-machine-102081.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.0.184:43735/

SUMMARY
========

PARAMETERS
 * /pick_and_place_state_machine/planning_group: arm
 * /pick_and_place_state_machine/robot_name: om_with_tb3
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    pick_and_place_state_machine (open_manipulator_with_tb3_tools/pick_and_place_state_machine)

ROS_MASTER_URI=http://192.168.0.184:11311

process[pick_and_place_state_machine-1]: started with pid [102098]
[INFO] [1571887362.402618]: State machine starting in initial state 'GO_TO_THE_LEFT_ROOM' with userdata:
    []
[WARN] [1571887362.403162]: Still waiting for action server 'om_with_tb3/move_base' to start... is it running?
[INFO] [1571887362.590641]: Connected to action server 'om_with_tb3/move_base'.
[INFO] [1571887376.893206]: State machine transitioning 'GO_TO_THE_LEFT_ROOM':'succeeded'-->'GO_TO_THE_OBJECT'
[INFO] [1571887441.995010]: State machine transitioning 'GO_TO_THE_OBJECT':'succeeded'-->'GET_CLOSER_TO_OBJECT'
[ERROR] [1571887441.996517]: InvalidUserCodeError: Could not execute state 'GET_CLOSER_TO_OBJECT' of type '<__main__.getCloserToGoal object at 0x7f278a747dd0>': Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/ubuntu/catkin_ws/src/open_manipulator_with_tb3/open_manipulator_with_tb3_tools/nodes/pick_and_place_state_machine", line 185, in execute
    if self.ar_marker_pose == False:
AttributeError: 'getCloserToGoal' object has no attribute 'ar_marker_pose'

Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/src/open_manipulator_with_tb3/open_manipulator_with_tb3_tools/nodes/pick_and_place_state_machine", line 643, in <module>
    main()
  File "/home/ubuntu/catkin_ws/src/open_manipulator_with_tb3/open_manipulator_with_tb3_tools/nodes/pick_and_place_state_machine", line 636, in main
    outcome = task_center.execute()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 359, in execute
    container_outcome = self._update_once()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 254, in _update_once
    + traceback.format_exc())
smach.exceptions.InvalidUserCodeError: Could not execute state 'GET_CLOSER_TO_OBJECT' of type '<__main__.getCloserToGoal object at 0x7f278a747dd0>': Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once
    self._remappings[self._current_label]))
  File "/home/ubuntu/catkin_ws/src/open_manipulator_with_tb3/open_manipulator_with_tb3_tools/nodes/pick_and_place_state_machine", line 185, in execute
    if self.ar_marker_pose == False:
AttributeError: 'getCloserToGoal' object has no attribute 'ar_marker_pose'

^[[A^C[pick_and_place_state_machine-1] killing on exit
^C^C[pick_and_place_state_machine-1] escalating to SIGTERM
[pick_and_place_state_machine-1] escalating to SIGKILL
Shutdown errors:
 * process[pick_and_place_state_machine-1, pid 102098]: required SIGKILL. May still be running.
shutting down processing monitor...
... shutting down processing monitor complete
```

**Comment by EndlessLoops** [comment]
@routiful

**Comment by JaehyunShim** [comment]
The corresponding demo will not be supported. If you have any questions about the usage of AR marker, please leave them at the [link](https://github.com/ros-perception/ar_track_alvar) 

Ryan
